# Generated by Django 4.1.5 on 2023-04-23 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balvikas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balvikas_member_subscription',
            name='Date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='balvikas_member_subscription',
            name='Year',
            field=models.IntegerField(choices=[(2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023)], default=2023, verbose_name='year'),
        ),
    ]
