# Generated by Django 4.1.5 on 2023-04-23 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekta', '0002_alter_ekta_member_subscription_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annual_Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(null=True, upload_to='Metting_photo')),
                ('Date', models.DateTimeField(null=True)),
                ('Discription', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='ekta_member_subscription',
            name='Date',
            field=models.DateTimeField(),
        ),
    ]
