# Generated by Django 4.1.5 on 2023-05-21 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekta', '0003_annual_meeting_alter_ekta_member_subscription_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annual_Function',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(null=True, upload_to='Function_photo')),
                ('Date', models.DateTimeField(null=True)),
                ('Discription', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='annual_meeting',
            name='Image',
            field=models.ImageField(null=True, upload_to='Meeting_photo'),
        ),
    ]
